### ISSUE TITLE
save as raw binary vs .prg format

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [datatrash/mos#167]
Suggestion adding raw binary output vs just exporting .prg ( with the 2 byte header ) would be useful for other platforms.
alternatively allow writing segments to separate files ?

**Comment by JettMonstersGoBoom** [comment]
I made some minor changes to build.rs to add file extension support to the config. and only output the 2 byte header if that extension is .prg which works for now. though I don't know Rust AT ALL so it's likely the worst way to do it :)

**Comment by sagacity** [comment]
Ha, excellent! What I'll probably do is add a configuration option in `mos.toml` so that you can choose to write a `prg`, a `raw` or write every segment to its own file (based on the segment name). I suppose that would cover your needs for now, right?

**Comment by JettMonstersGoBoom** [comment]
So long as you can specify the output extension I think that'll work. 
For example I put in the toml
output="NES" 
Which shortcuts the 2 byte write ( only "prg" does that ) and saves as main.nes

**Comment by JettMonstersGoBoom** [comment]
the other "option" is to add header information into the toml file. the way Millfork does this is quite flexible ( but maybe too much ) raw binary is fine though I had to fiddle with segments to get the output I expect with the header encoded inside the asm file.

**Comment by sagacity** [comment]
I can definitely take a look at how Millfork does it. Do you happen to have a direct link to the docs for that feature?

**Comment by JettMonstersGoBoom** [comment]
the output section of this doc https://github.com/KarolS/millfork/blob/master/docs/api/custom-platform.md

**Comment by sagacity** [comment]
I've added a few ways to output files now. You can see the details in the commit linked above, but the idea is you can now output a prg, a raw binary, or a raw binary per segment. You can also override the filenames of the prg/bin and also of the individual segments. If you give multiple segments the same filename, those segments will still be merged together.
